### PR TITLE
Add Stephen D'Angelo to AUTHORS

### PR DESCRIPTION
**Pull request by ChALkeR**
/cc @stephenmdangelo

### CODE REVIEW

**Comment by stephenmdangelo** [comment]
Thanks! Would it be possible to use my @gmail address instead? I just forgot to properly set my git settings when I cloned this repo.

**Comment by ChALkeR** [comment]
@stephenmdangelo Yes, of course. Could you file an alternative PR or post your preferred email here, then?

**Comment by stephenmdangelo** [comment]
Great, thanks. stephen.m.dangelo@gmail.com

**Comment by ChALkeR** [comment]
@stephenmdangelo Updated, PTAL.

**Comment by stephenmdangelo** [comment]
LGTM. Thanks again.

**Comment by ChALkeR** [comment]
Merged, thanks!

**Pull request merged**
